/**
 * The ISO 639-1 language set, with English names for the prompt and endonyms so a reader
 * can spot their own language. Generated from Intl.DisplayNames rather than hand-typed.
 *
 * The stored preference is the English name, because that is what the prompt sends to
 * the model as the target language.
 */
export interface ReadingLanguage {
  code: string;
  name: string;
  /** The language written in itself. Empty when it matches the English name. */
  native: string;
}

export const READING_LANGUAGES: readonly ReadingLanguage[] = [
  { code: "ab", name: "Abkhazian", native: "" },
  { code: "aa", name: "Afar", native: "" },
  { code: "af", name: "Afrikaans", native: "" },
  { code: "ak", name: "Akan", native: "" },
  { code: "tw", name: "Akan", native: "" },
  { code: "sq", name: "Albanian", native: "shqip" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "an", name: "Aragonese", native: "" },
  { code: "hy", name: "Armenian", native: "հայերեն" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "av", name: "Avaric", native: "" },
  { code: "ae", name: "Avestan", native: "" },
  { code: "ay", name: "Aymara", native: "" },
  { code: "az", name: "Azerbaijani", native: "azərbaycan" },
  { code: "bm", name: "Bambara", native: "bamanakan" },
  { code: "bn", name: "Bangla", native: "বাংলা" },
  { code: "ba", name: "Bashkir", native: "башҡорт" },
  { code: "eu", name: "Basque", native: "euskara" },
  { code: "be", name: "Belarusian", native: "беларуская" },
  { code: "bi", name: "Bislama", native: "" },
  { code: "bs", name: "Bosnian", native: "bosanski" },
  { code: "br", name: "Breton", native: "brezhoneg" },
  { code: "bg", name: "Bulgarian", native: "български" },
  { code: "my", name: "Burmese", native: "မြန်မာ" },
  { code: "ca", name: "Catalan", native: "català" },
  { code: "ch", name: "Chamorro", native: "" },
  { code: "ce", name: "Chechen", native: "нохчийн" },
  { code: "zh", name: "Chinese", native: "中文" },
  { code: "cu", name: "Church Slavic", native: "" },
  { code: "cv", name: "Chuvash", native: "чӑваш чӗлхи" },
  { code: "kw", name: "Cornish", native: "kernewek" },
  { code: "co", name: "Corsican", native: "" },
  { code: "cr", name: "Cree", native: "" },
  { code: "hr", name: "Croatian", native: "hrvatski" },
  { code: "cs", name: "Czech", native: "čeština" },
  { code: "da", name: "Danish", native: "dansk" },
  { code: "dv", name: "Divehi", native: "" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "dz", name: "Dzongkha", native: "རྫོང་ཁ" },
  { code: "en", name: "English", native: "" },
  { code: "eo", name: "Esperanto", native: "" },
  { code: "et", name: "Estonian", native: "eesti" },
  { code: "ee", name: "Ewe", native: "eʋegbe" },
  { code: "fo", name: "Faroese", native: "føroyskt" },
  { code: "fj", name: "Fijian", native: "" },
  { code: "tl", name: "Filipino", native: "" },
  { code: "fi", name: "Finnish", native: "suomi" },
  { code: "fr", name: "French", native: "français" },
  { code: "ff", name: "Fula", native: "Pulaar" },
  { code: "gl", name: "Galician", native: "galego" },
  { code: "lg", name: "Ganda", native: "Luganda" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "gn", name: "Guarani", native: "" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "ht", name: "Haitian Creole", native: "" },
  { code: "ha", name: "Hausa", native: "" },
  { code: "he", name: "Hebrew", native: "עברית" },
  { code: "hz", name: "Herero", native: "" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "ho", name: "Hiri Motu", native: "" },
  { code: "hu", name: "Hungarian", native: "magyar" },
  { code: "is", name: "Icelandic", native: "íslenska" },
  { code: "io", name: "Ido", native: "" },
  { code: "ig", name: "Igbo", native: "" },
  { code: "id", name: "Indonesian", native: "Indonesia" },
  { code: "ia", name: "Interlingua", native: "interlingua" },
  { code: "ie", name: "Interlingue", native: "" },
  { code: "iu", name: "Inuktitut", native: "" },
  { code: "ik", name: "Inupiaq", native: "" },
  { code: "ga", name: "Irish", native: "Gaeilge" },
  { code: "it", name: "Italian", native: "italiano" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "jv", name: "Javanese", native: "Jawa" },
  { code: "kl", name: "Kalaallisut", native: "kalaallisut" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "kr", name: "Kanuri", native: "" },
  { code: "ks", name: "Kashmiri", native: "کٲشُر" },
  { code: "kk", name: "Kazakh", native: "қазақ тілі" },
  { code: "km", name: "Khmer", native: "ខ្មែរ" },
  { code: "ki", name: "Kikuyu", native: "Gikuyu" },
  { code: "rw", name: "Kinyarwanda", native: "Ikinyarwanda" },
  { code: "kv", name: "Komi", native: "" },
  { code: "kg", name: "Kongo", native: "" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "kj", name: "Kuanyama", native: "" },
  { code: "ku", name: "Kurdish", native: "kurdî (kurmancî)" },
  { code: "ky", name: "Kyrgyz", native: "кыргызча" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "la", name: "Latin", native: "" },
  { code: "lv", name: "Latvian", native: "latviešu" },
  { code: "li", name: "Limburgish", native: "" },
  { code: "ln", name: "Lingala", native: "lingála" },
  { code: "lt", name: "Lithuanian", native: "lietuvių" },
  { code: "lu", name: "Luba-Katanga", native: "Tshiluba" },
  { code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch" },
  { code: "mk", name: "Macedonian", native: "македонски" },
  { code: "mg", name: "Malagasy", native: "" },
  { code: "ms", name: "Malay", native: "Melayu" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "mt", name: "Maltese", native: "Malti" },
  { code: "gv", name: "Manx", native: "Gaelg" },
  { code: "mi", name: "Māori", native: "" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "mh", name: "Marshallese", native: "" },
  { code: "mn", name: "Mongolian", native: "монгол" },
  { code: "na", name: "Nauru", native: "" },
  { code: "nv", name: "Navajo", native: "" },
  { code: "ng", name: "Ndonga", native: "" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "nd", name: "North Ndebele", native: "isiNdebele" },
  { code: "se", name: "Northern Sami", native: "davvisámegiella" },
  { code: "no", name: "Norwegian", native: "norsk" },
  { code: "nb", name: "Norwegian Bokmål", native: "norsk bokmål" },
  { code: "nn", name: "Norwegian Nynorsk", native: "norsk nynorsk" },
  { code: "ny", name: "Nyanja", native: "" },
  { code: "oc", name: "Occitan", native: "occitan" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "oj", name: "Ojibwa", native: "" },
  { code: "om", name: "Oromo", native: "Oromoo" },
  { code: "os", name: "Ossetic", native: "ирон" },
  { code: "pi", name: "Pali", native: "" },
  { code: "ps", name: "Pashto", native: "پښتو" },
  { code: "fa", name: "Persian", native: "فارسی" },
  { code: "pl", name: "Polish", native: "polski" },
  { code: "pt", name: "Portuguese", native: "português" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "qu", name: "Quechua", native: "Runasimi" },
  { code: "ro", name: "Romanian", native: "română" },
  { code: "rm", name: "Romansh", native: "rumantsch" },
  { code: "rn", name: "Rundi", native: "Ikirundi" },
  { code: "ru", name: "Russian", native: "русский" },
  { code: "sm", name: "Samoan", native: "" },
  { code: "sg", name: "Sango", native: "Sängö" },
  { code: "sa", name: "Sanskrit", native: "संस्कृत भाषा" },
  { code: "sc", name: "Sardinian", native: "sardu" },
  { code: "gd", name: "Scottish Gaelic", native: "Gàidhlig" },
  { code: "sr", name: "Serbian", native: "српски" },
  { code: "sn", name: "Shona", native: "chiShona" },
  { code: "ii", name: "Sichuan Yi", native: "ꆈꌠꉙ" },
  { code: "sd", name: "Sindhi", native: "سنڌي" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "sk", name: "Slovak", native: "slovenčina" },
  { code: "sl", name: "Slovenian", native: "slovenščina" },
  { code: "so", name: "Somali", native: "Soomaali" },
  { code: "nr", name: "South Ndebele", native: "" },
  { code: "st", name: "Southern Sotho", native: "Sesotho" },
  { code: "es", name: "Spanish", native: "español" },
  { code: "su", name: "Sundanese", native: "Basa Sunda" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "ss", name: "Swati", native: "" },
  { code: "sv", name: "Swedish", native: "svenska" },
  { code: "ty", name: "Tahitian", native: "" },
  { code: "tg", name: "Tajik", native: "тоҷикӣ" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "tt", name: "Tatar", native: "татар" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "bo", name: "Tibetan", native: "བོད་སྐད་" },
  { code: "ti", name: "Tigrinya", native: "ትግርኛ" },
  { code: "to", name: "Tongan", native: "lea fakatonga" },
  { code: "ts", name: "Tsonga", native: "" },
  { code: "tn", name: "Tswana", native: "Setswana" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "tk", name: "Turkmen", native: "türkmen dili" },
  { code: "uk", name: "Ukrainian", native: "українська" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "ug", name: "Uyghur", native: "ئۇيغۇرچە" },
  { code: "uz", name: "Uzbek", native: "o‘zbek" },
  { code: "ve", name: "Venda", native: "" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "vo", name: "Volapük", native: "" },
  { code: "wa", name: "Walloon", native: "" },
  { code: "cy", name: "Welsh", native: "Cymraeg" },
  { code: "fy", name: "Western Frisian", native: "Frysk" },
  { code: "wo", name: "Wolof", native: "" },
  { code: "xh", name: "Xhosa", native: "IsiXhosa" },
  { code: "yi", name: "Yiddish", native: "ייִדיש" },
  { code: "yo", name: "Yoruba", native: "Èdè Yorùbá" },
  { code: "za", name: "Zhuang", native: "Vahcuengh" },
  { code: "zu", name: "Zulu", native: "isiZulu" },
];

const BY_NAME = new Map(
  READING_LANGUAGES.map((entry) => [entry.name.toLowerCase(), entry]),
);
const BY_CODE = new Map(READING_LANGUAGES.map((entry) => [entry.code, entry]));

export const DEFAULT_LANGUAGE_NAME = "English";

/**
 * Resolve whatever the browser reports, or a previously stored value, to a language name.
 * Accepts a name ("Turkish"), a tag ("tr-TR"), or a bare code ("tr").
 */
export function resolveLanguageName(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) return DEFAULT_LANGUAGE_NAME;

  const byName = BY_NAME.get(trimmed.toLowerCase());
  if (byName) return byName.name;

  const base = trimmed.toLowerCase().split(/[-_]/u)[0] ?? "";
  return BY_CODE.get(base)?.name ?? DEFAULT_LANGUAGE_NAME;
}

/** The label shown in the picker: English name first, so type-ahead matches it. */
export function languageLabel(entry: ReadingLanguage): string {
  return entry.native ? entry.name + " \u2014 " + entry.native : entry.name;
}
